Tiny Bubbles/force-app/main/default/objects/Brewery__c/Brewery__c.object-meta.xml
<CustomObject>
    <label>Brewery</label>
    <nameField>
        <label>Brewery Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Breweries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Tiny Bubbles/force-app/main/default/objects/Brewery__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Breweries</relationshipLabel>
    <relationshipName>Breweries</relationshipName>
    <type>Lookup</type>
</CustomField>

Tiny Bubbles/force-app/main/default/objects/Brewery__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>micro</fullName>
            </value>
            <value>
                <fullName>regional</fullName>
            </value>
            <value>
                <fullName>brewpub</fullName>
            </value>
            <value>
                <fullName>large</fullName>
            </value>
            <value>
                <fullName>planning</fullName>
            </value>
            <value>
                <fullName>bar</fullName>
            </value>
            <value>
                <fullName>contract</fullName>
            </value>
            <value>
                <fullName>proprietor</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Tiny Bubbles/force-app/main/default/classes/UserSavedListController.cls
public class UserSavedListController {

    @AuraEnabled
    public static List<Brewery__c> getSavedList(){
        ID userId = System.UserInfo.getUserId();
        User userContactId = [Select ContactId FROM USER WHERE ID = :userId] ;
        List<Brewery__c> savedBreweries = new List<Brewery__c>();
        for (Brewery__c brew : [SELECT Name, Type__c FROM Brewery__c WHERE Contact__c = :userContactId.ContactId]) {
            savedBreweries.add(brew);            
        }
        return savedBreweries;
    }
}